image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn clean package
          - apt-get update
          #Get cloudfoundry CLI
          - wget -O /tmp/cf-cli.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.40.0"
          - ls -alF /tmp/
          - mkdir -p /usr/local/bin
          - tar -xzf /tmp/cf-cli.tgz -C /usr/local/bin
          - cf --version
          - cf login -a https://api.run.pivotal.io -u $PIVOTAL_USERNAME -p $PIVOTAL_PASSWORD
          - cf push
